### ISSUE TITLE
‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by ghost** [enten/angular-universal#10]
failed to run `npm run dev` and got following error:

`> ng-universal@0.0.0 dev /media/pchauhan13/work/repos/angular-universal
> ng-udkc

/usr/bin/env: ‘node\r’: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ng-universal@0.0.0 dev: `ng-udkc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng-universal@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by enten** [comment]
@pchauhan13  
Can you share a repository which reproduce your issue?

Can you try to run the next command line in the cwd `/media/pchauhan13/work/repos/angular-universal` and send the output?
```sh
./node_modules/.bin/ng-udkc
```

**Comment by TobiasKrogh** [comment]
@enten Although I could not yet jump deep into it, the project looks like a good starting point so thanks for providing

I encountered the same issue after clone and install

```
$ ./node_modules/.bin/ng-udkc
env: node\r: No such file or directory
```

```
$ which node
/usr/local/bin/node
$ /usr/local/bin/node -v
v10.5.0
```

Node is properly installed and I can even use it in another project, I am unsure why `#!/usr/bin/env node` creates this hassle. Just for more information:

Using MacOS High Sierra 10.13.5 with mentioned Node version.

**Comment by enten** [comment]
Can you tried to open in your projet `./node_modules/.bin/ng-udkc` (it's a symbolic link to the right file) and remove the first line?

```diff
-#!/usr/bin/env node

try {
    var localUdkc = require.resolve(path.join(process.cwd(), "node_modules", "udk", "angular", "bin",
```

When it's done, tried to run from the root of your project: `node ./node_modules/.bin/ng-udkc`.

**Can you share the console output?**

**Comment by madibi** [comment]
> after remove -#!/usr/bin/env node

`ENOENT: no such file or directory, open 'C:\C\x-un-ang\03\my-project\node_modules\@angular\cli\commands\run.json'
Error: ENOENT: no such file or directory, open 'C:\C\x-un-ang\03\my-project\node_modules\@angular\cli\commands\run.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at findCommand (C:\x-un-ang\03\my-project\node_modules\@angular\cli\models\command-runner.js:302:31)
    at Object.<anonymous> (C:\x-un-ang\03\my-project\node_modules\@angular\cli\models\command-runner.js:77:45)
    at Generator.next (<anonymous>)
    at C:\x-un-ang\03\my-project\node_modules\@angular\cli\models\command-runner.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\x-un-ang\03\my-project\node_modules\@angular\cli\models\command-runner.js:10:12)
    at Object.runCommand (C:\x-un-ang\03\my-project\node_modules\@angular\cli\models\command-runner.js:51:12)
    at C:\x-un-ang\03\my-project\node_modules\@angular\cli\lib\cli\index.js:38:58
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-universal@0.0.0 build:prod: `ng run ng-universal:udk:production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-universal@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\silverfuture\AppData\Roaming\npm-cache\_logs\2018-09-05T06_30_15_937Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-universal@0.0.0 prestart: `npm run build:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-universal@0.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\silverfuture\AppData\Roaming\npm-cache\_logs\2018-09-05T06_30_15_956Z-debug.log`

**Comment by ghost** [comment]
The issue seems to be emerging after the upgraded node and angular

**Comment by enten** [comment]
@madibi @pchauhan13 
Which versions did you used? (os, node, npm, udk, angular packages).

I would like to reproduce your issue to be able to investigate.
