### ISSUE TITLE
Unknown option: '--deployUrl'

### ISSUE THREAD

**Issue by mixalistzikas** [enten/angular-universal#11]
I think you are the only guy who can help me solve this issue

I create an example too... https://github.com/mixalistzikas/angular-ssr-i18n
But when I run `npm run build:all`
I get this error: `Unknown option: '--deployUrl'`

Any suggestions. I know this is not your project but I'm trying to find a solution and none can help me.

**Comment by enten** [comment]
I tried to clone your repo and run `npm run build:all`: it's work very well.

When I open `localhost:4201/el`, instead of _Hello World_, I see _Γεια σου κόσμε_.

It's seems you fixed your project in the way that you want. Great works!
