### ISSUE TITLE
can't build with certain packages

### ISSUE THREAD

**Issue by karwank** [enten/angular-universal#13]
I can't preform build when I use certain packages. For example `ngforage`.

<pre>
~/ng-app$ npm run dev

> ng-universal@0.0.0 dev /home/deploy/ng-app
> ng-udkc

[udk] > bootstrap container
[udk] >> container up
[udk] >>> prepare webpack config
[udk] >>> prepare webpack compiler
[udk] >>> compiler done                                                                                            
[udk] >>> compiler watching...
/home/deploy/ng-app/node_modules/localforage/src/utils/serializer.js:2
import createBlob from './createBlob';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /home/deploy/ng-app/node_modules/ngforage/bundles/ngforage.umd.js:67:19
    at Object.setPrototypeOf.__proto__ (/home/deploy/ng-app/node_modules/ngforage/bundles/ngforage.umd.js:26:65)
    at Object.<anonymous> (/home/deploy/ng-app/node_modules/ngforage/bundles/ngforage.umd.js:29:2)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
</pre>

I used to fix it by adding this code to webpack.server.config.js. But it doesn't work with udk.

<pre>
// Work around for https://github.com/angular/angular-cli/issues/7200

const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: {
    server: './server.ts',
  },
  target: 'node',
  resolve: { extensions: ['.ts', '.js'] },
  externals: [/(node_modules|main\..*\.js)/,],
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  module: {
    rules: [
      { test: /\.ts$/, loader: 'ts-loader' }
    ]
  },
  optimization: {
    minimize: false
  },
  plugins: [
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, 'src'), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, 'src'),
      {}
    )
  ]
}
</pre>

How can I implement it with this repository?

**Comment by enten** [comment]
When you use [angular-cli](https://cli.angular.io/): webpack configs are generated dynamically. And currently, there is no way to mutate these configurations.

I think that your issue is due to an import as like below:

```ts
import * as localforageUtils from 'localforage/src/utils/serializer';
```

That kind of import isn't a problem for a target browser: because all dependencies are bundled.

[But for a target server: by default, external dependencies aren't bundled](https://github.com/angular/angular-cli/blob/v6.2.0-beta.1/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts#L34). So, dependencies are imported on runtime. And yes: the code imported can't be run by nodejs. The code must be "compile" to be run by nodejs.

With angular-cli, your have once way to fix that: using option `bundleDependencies` with value `"all"` for your target server to bundle all external dependencies.

**Can you try [that solution as I described here](https://github.com/enten/angular-universal/issues/2#issuecomment-387314558) and give us a feedback?**

If that works, I will give you a better solution: we will mutate the server webpack configuration generated dynamically by angular-cli before it was run.

**Comment by karwank** [comment]
> With angular-cli, your have once way to fix that: using option bundleDependencies with value "all" for your target server to bundle all external dependencies.

Thank you for your reposne, I already tried to add this option, but probably in a wrong place. I added it in file angular.json under:

<pre>
"ng-universal": {
      "root": "",
      "projectType": "application",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/app/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.browser.json",
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "bundleDependencies": "all"
            }
          }
</pre>

Should it be added in this place?

**Comment by karwank** [comment]
> Can you try that solution as I described here and give us a feedback?
> 
> If that works, I will give you a better solution: we will mutate the server webpack configuration generated dynamically by angular-cli before it was run

Sorry, I didn's see that link. A new error show up, but it probably is something else.
<pre>
WARNING in ./node_modules/express/lib/view.js
81:13-25 Critical dependency: the request of a dependency is an expression
</pre>

However. It works, all packages now are included to dist/server/main.js file.

**Comment by enten** [comment]
@karwank
It's not an error: just [a warn message triggered by that line in express source code](https://github.com/expressjs/express/blob/4.16.3/lib/view.js#L81).

Right: the source of your issue is the one that expected.

A better solution is to dynamically mutate webpack configuration of the target server to bundle required dependencies for runtime only (like ngforage).

If you are interested: do you have a public repository to do the patch for your code?

**Comment by karwank** [comment]
Yes, please look at https://github.com/karwank/dealersite-ng-app.

**Comment by enten** [comment]
**Can you try to apply patch below on your repostiroy after commit [karwank/dealersite-ng-app/7ffbb209](https://github.com/karwank/dealersite-ng-app/commit/7ffbb2092f00a9eef13e9cf015182424431bff71) and give us a feedback if it's works?**

Patch's purpose: externalize all node dependencies for the target server and mutate its webpack configuration on runtime to bundle [ngforage](https://github.com/Alorel/ngforage) and [localforage](https://github.com/localForage/localForage) dependencies.

```diff
diff --git a/angular.json b/angular.json
index e799eb1..8a46a83 100644
--- a/angular.json
+++ b/angular.json
@@ -70,7 +70,7 @@
             "outputPath": "dist/app/server",
             "main": "src/main.server.ts",
             "tsConfig": "src/tsconfig.server.json",
-            "bundleDependencies": "all"
+            "bundleDependencies": "none"
           },
           "configurations": {
             "production": {
@@ -88,7 +88,8 @@
           "options": {
             "main": "src/main.server.ts",
             "browserTarget": "ng-universal:build",
-            "serverTarget": "ng-universal:server"
+            "serverTarget": "ng-universal:server",
+            "partialServerConfig": "webpack.server.config.js"
           },
           "configurations": {
             "production": {
@@ -177,4 +178,4 @@
       "spec": false
     }
   }
-}
\ No newline at end of file
+}
diff --git a/udk.container.js b/udk.container.js
index 09a537f..01949bb 100644
--- a/udk.container.js
+++ b/udk.container.js
@@ -10,7 +10,8 @@ module.exports = {
     'src/tsconfig.server.json',
     'src/index.html',
     'src/main.server.ts',
-    'tsconfg.json'
+    'tsconfg.json',
+    'webpack.server.config.js',
   ],
 
   bootstrap(proc, configPath) {
diff --git a/webpack.server.config.js b/webpack.server.config.js
new file mode 100644
index 0000000..d3743c7
--- /dev/null
+++ b/webpack.server.config.js
@@ -0,0 +1,15 @@
+module.exports = function (config) {
+  const originExternalFn = config.externals[1];
+
+  config.externals[1] = (_, request, callback) => {
+    if (
+      request.startsWith('ngforage') ||
+      request.startsWith('localforage')
+    ) {
+        return callback();
+    }
+
+    originExternalFn(_, request, callback);
+  };
+};
+
```

**Comment by karwank** [comment]
Thank you. It works.

As I understand by this additional code in `webpack.server.config.js` file I define which package should be bundled in main.js file and all other packages will be just taken from `node_modules`.

However, I deploy my code to AWS Lamda service and it would be better to not attach whole node_modules directory to zip file. It would be better to bundle almost all packages to `main.js` just without those packages which could cause `Critical dependency`. This is exactly how my previous configuration worked,

This `externals: [/(node_modules|main\..*\.js)/,],` was allowing to bundle all packages, but following code was responsible for excluding those unnecessary.

<pre>
plugins: [
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, 'src'), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, 'src'),
      {}
    )
  ]
</pre>

So is it possibe have `"bundleDependencies": "all"` and just exclude some packages, instead of pointing one by one which should be bundled? Or could I just modify your code to return callback for almost all requests expect those unnecessary?

**Comment by enten** [comment]
> So is it possibe have `"bundleDependencies": "all"` and just exclude some packages, instead of pointing one by one which should be bundled?

Of course: you need to adjust `webpack.server.config.js` only.

**Can we consider your initial issue as resolved?**

```js
// please note that option bundleDependencies in angular.json
// will not affect build and dev scripts

module.exports = function (config) {
  config.externals = (_, request, callback) => {
    if (
      request.startsWith('dep1-to-exclude-frm-server-bundle') ||
      request.startsWith('dep2-to-exclude-frm-server-bundle')
    ) {
      callback(null, request);
    }

    return callback();
  };
};
```
