### ISSUE TITLE
SSR APP_INITIALIZER HttpClient error

### ISSUE THREAD

**Issue by xiongyayun428** [enten/angular-universal#22]
```ts
@NgModule({
  declarations: [AppComponent, HomeComponent],
  imports: [
    BrowserModule.withServerTransition({ appId: 'my-app' }),
    RouterModule.forRoot([
      { path: '', component: HomeComponent, pathMatch: 'full' },
      { path: 'lazy', loadChildren: './lazy/lazy.module#LazyModule' },
      { path: 'lazy/nested', loadChildren: './lazy/lazy.module#LazyModule' }
    ]),
    HttpClientModule,
    TransferHttpCacheModule,
    StartupModule.forRoot('/assets/config/app.json'),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

```ts
import { NgModule, ModuleWithProviders, APP_INITIALIZER } from '@angular/core';
import { StartupService, STARTUP_CONFIG } from './startup.service';
import { HttpClientModule } from '@angular/common/http';

@NgModule({
  imports: [
    HttpClientModule
  ],
})
export class StartupModule {
  static forRoot(startupConfig: string): ModuleWithProviders<StartupModule> {
    return {
      ngModule: StartupModule,
      providers: [
        { provide: STARTUP_CONFIG, useValue: startupConfig },
        StartupService,
        {
          provide: APP_INITIALIZER,
          useFactory: StartupServiceFactory,
          deps: [StartupService, STARTUP_CONFIG],
          multi: true,
        }
      ]
    };
  }
}

export function StartupServiceFactory(startService: StartupService, config: string): Function {
  return () => startService.load(config).then(resp => console.log(resp));
}
```

```ts
import { Injectable, InjectionToken } from '@angular/core';
import { HttpClient } from '@angular/common/http';

export const STARTUP_CONFIG = new InjectionToken<string>(
  'STARTUP_CONFIG'
);

@Injectable()
export class StartupService {
  constructor(private client: HttpClient) {}

  load(config: string): Promise<any> {
    return this.client
      .get(config)
      .toPromise()
      .catch(error => {
        console.error(`==========================================`, error);
      });
  }
}
```

result:
![image](https://user-images.githubusercontent.com/11458959/50207275-f3222100-03a8-11e9-965b-2b8622a02662.png)

use `StartupModule.forRoot('./assets/config/app.json')` is error
use `StartupModule.forRoot('http://localhost:4000/assets/config/app.json')` is successed

**Comment by enten** [comment]
The value given to `StartupModule.forRoot()` is used to provide `STARTUP_CONFIG` token.
The factory provider `StartupServiceFactory()` uses the `STARTUP_CONFIG` token value with `StartupService.prototype.load()`.

So with instruction `StartupModule.forRoot('./assets/config/app.json')`: the `StartupService.prototype.load()` is called with `'./assets/config/app.json'` a kind of relative path.
Whereas with instruction `StartupModule.forRoot('http://localhost:4000/assets/config/app.json')`: the `StartupService.prototype.load()` is called with `'http://localhost:4000/assets/config/app.json'`.

**Can you try value: `/assets/config/app.json`? May the absolute root while be resolved corretly?**

Have you a repo which reproduce your issue? I can try to fix that.

**Comment by xiongyayun428** [comment]
> The value given to `StartupModule.forRoot()` is used to provide `STARTUP_CONFIG` token.
> The factory provider `StartupServiceFactory()` uses the `STARTUP_CONFIG` token value with `StartupService.prototype.load()`.
> 
> So with instruction `StartupModule.forRoot('./assets/config/app.json')`: the `StartupService.prototype.load()` is called with `'./assets/config/app.json'` a kind of relative path.
> Whereas with instruction `StartupModule.forRoot('http://localhost:4000/assets/config/app.json')`: the `StartupService.prototype.load()` is called with `'http://localhost:4000/assets/config/app.json'`.
> 
> **Can you try value: `/assets/config/app.json`? May the absolute root while be resolved corretly?**
> 
> Have you a repo which reproduce your issue? I can try to fix that.

https://stackblitz.com/edit/universal-starter
