### ISSUE TITLE
environment.ts / environment-prod.ts

### ISSUE THREAD

**Issue by gonzalo-roberto-diaz** [enten/angular-universal#23]
Hello. 
When building the application for distribution  with 
```
npm start
```
I would like to know which of these 2 files, `environment.ts`  or  `environment-prod.ts`, is the one whose values are used.

There doesn't seem to be any difference on how you build, since the `prestart` step in  `package.json` is always set to `prod`
```
   ...
    "prestart": "npm run build:prod",
   ...
```

Is there a way to control which file's values are used? Are they both used, but at different moments during the application execution?

**Comment by enten** [comment]
@gonzalo-roberto-diaz 

To understand which file is used (between `environment.ts` and `environment.prod.ts` you need to be familiar with the [angular CLI](https://angular.io/cli/build) and [its workspace configuration (the `angular.json` file)](https://angular.io/guide/workspace-config).

In some [architect builders](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular/src) (which are used under the hood by the angular CLI): you can specify [`fileReplacements` option](https://angular.io/guide/workspace-config#additional-build-and-test-options).

**The `fileReplacements` option can be used to override some imports when webpack is building without change any instruction in your code**.

[You can check in the `angular.json` that we use `fileReplacements`](https://github.com/enten/angular-universal/blob/d63badb/angular.json#L38) option for production configs as below:

```json
"fileReplacements": [
  {
    "replace": "src/environments/environment.ts",
    "with": "src/environments/environment.prod.ts"
  }
],
```

Finally, you can check in the package.json the two commands below:

```json
"build": "ng run angular:udk",
"build:prod": "ng run angular:udk:production",
```

These scripts use the [udk builder for angular](https://github.com/enten/udk/tree/master/angular) which can run browser and server builds in sequential way. The [udk builder target is declared in `angular.json`](https://github.com/enten/angular-universal/blob/d63badb/angular.json#L86) as below:

```json
"udk": {
  "builder": "udk:udk-builder",
  "options": {
    "browserTarget": "angular:build",
    "serverTarget": "angular:server"
  },
  "configurations": {
    "production": {
      "browserTarget": "angular:build:production",
      "serverTarget": "angular:server:production",
      "verbose": true
    }
  }
}
```

So, when we run command `build:prod`, we run [`build`](https://github.com/enten/angular-universal/blob/d63badb/angular.json#L11) and [`server`](https://github.com/enten/angular-universal/blob/d63badb/angular.json#L67) builds with their production configuration.

_That's all! I hope that these details will help you to understand how we can use the `environment.prod.ts` in production build without import it. Keep in mind that angular builders are responsibles to replace instructions `import 'environment'` by `import 'environment.prod'` (during webpack build) as specified by the `fileReplacement` option_.

**Comment by gonzalo-roberto-diaz** [comment]
Thank you for this useful overview, @enten !

Then,  to summarize the behavior:

- the `environment.prod.ts` values are __always__ used for whenever we build we build, with whatever parameters, since `build:prod` is hard-coded in the prestart clause
- the `environment.prod.ts` are also used when we do an `npm start` because that triggers a build to be served in production.
- the `environment.ts` values are used when we run locally with a simple `ng serve`
