### ISSUE TITLE
can't add global["document"] in main.server.ts

### ISSUE THREAD

**Issue by aldiiii** [enten/angular-universal#25]
this code

const domino = require("domino");
const fs = require("fs");
const path = require("path");
const templateA = fs
  .readFileSync(path.join("dist/app/browser", "index.html"))
  .toString();
const win = domino.createWindow(templateA);
win.Object = Object;
win.Math = Math;

global["window"] = win;
global["document"] = win.document;
global["branch"] = null;
global["object"] = win.object;

**Comment by enten** [comment]
I don't understand. That was your issue?

**Comment by aldiiii** [comment]
i run npm now-start.
i have get error log like this 
![image](https://user-images.githubusercontent.com/23220059/52129500-41923300-266a-11e9-9a2f-d819ceb09dfb.png)

I already add this code in main.server.ts but still document is not defined.

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const templateA = fs.readFileSync(path.join('dist/app/browser', 'index.html')).toString();
const win = domino.createWindow(templateA);

global['window'] = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
global['document'] = win.document;

could you help me ? 😢

**Comment by enten** [comment]
Yes, I will try.

Have you a public repository which reproduce your issue to investigate?

**Comment by enten** [comment]
Your issue isn't related with the repository but I think I found the cause of your issue.

Your code seems to try mocking `window` on server side. 

If you set `global['window']` early you will be able to use your `window` mock globally but not `document`.

**You need to declare `document` globally as an alias to your window mock.**

```ts
Object.defineProperty(global, 'document', { get: () => global['window'] });
```

**But the most important part is to override [`DOCUMENT` token](https://angular.io/api/common/DOCUMENT) in [server module](https://github.com/angular/angular/blob/7.2.2/packages/platform-server/src/server.ts#L32) with your `window.document` mock in the server module.**

If you don't override `DOCUMENT` token in the server module: your angular server render will works without the document from your window mock.

You can override `DOCUMENT` token when you create the [ngExpressEngine with extra providers](https://github.com/angular/universal/tree/master/modules/express-engine#extra-providers) (or as option with the [CompilerFactory](https://angular.io/api/core/CompilerFactory).

```ts
app.engine('html', ngExpressEngine({
  bootstrap: ServerAppModule,
  providers: [
    { provide: DOCUMENT, useValue: global['window'].document }
  ]
}));
```

_In my opinion, mocking window on server isn't a good practice. Why you want to mock window on server side?_
