### ISSUE TITLE
[question] now.sh deployment

### ISSUE THREAD

**Issue by jkhask** [enten/angular-universal#26]
Do you have a now.json that you did not include in the repo? I am trying to deploy an SSR angular app to now.sh and struggling on how to get it to work correctly. I cloned this repo and tried a now deployment but nothing happened on their end, it just uploaded the files. That's what's happening with my site.

**Comment by enten** [comment]
@jkhask  
The fact is that [now v2 was released the 8 nov 2018](https://zeit.co/blog/now-2) and the repository was initially setup to work with now v1.

The [build workflow](https://zeit.co/docs/v2/deployments/builds/) with now v2 is great but there is no builder optimized for angular universal application:

* [Static Builder](https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build/): works with angular as single page application ;
* [Node.js Server Builder](https://zeit.co/docs/v2/deployments/official-builders/node-js-server-now-node-server/): works with node server application.

I tried to combine the both builders but I don't succeed to make them works as expected.

I think we need to [write a builder](https://zeit.co/docs/v2/deployments/builders/developer-guide/) optimized for universal application.

**now v1 has more flexibility so we can still use it to deploy our angular universal application**

You can configure the version 1 in the `now.json` and don't forget to create `.nowignore` file to exclude `dist` and `node_modules` folders.

```patch
---------------------------------- .nowignore ----------------------------------
new file mode 100644
index 0000000..de4d1f0
@@ -0,0 +1,2 @@
+dist
+node_modules

----------------------------------- now.json -----------------------------------
new file mode 100644
index 0000000..87a0dd6
@@ -0,0 +1,4 @@
+{
+  "version": 1,
+  "name": "ng-universal"
+}
```

Finally run `now deploy` and that works well!

**Comment by abdurrahmanarikan** [comment]
seems we cannot use now 1 anymore
I've used your now.json and .nowignore files but still get the error:
Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade

**Comment by enten** [comment]
I tried again to deploy for now v2 with [Node.js Server Builder](https://zeit.co/docs/v2/deployments/official-builders/node-js-server-now-node-server/): I don't succeed too.

Below what I tried (patch at end of this post):
* remove scripts `now-build` adn `now-start` from `package.json` ;
* create `.nowignore` with content `node_modules` ;
* update `now.json` with version 2 and builders `{ "src": "./dist/app/server/main.js", "use": "@now/node-server" }` ;
* run `now deploy` and open url deployment.

I just see a file explorer which has file `./dist/app/server/main.js` only.

**May I don't understand how to deploy a node server (with others static assets) with now v2?**

If someone can help do not hesitate. Because the only I see to do what we need to deploy angular universal application with now v2 is to write a custom builder.

--
```diff
diff --git a/.nowignore b/.nowignore
index de4d1f0..3c3629e 100644
--- a/.nowignore
+++ b/.nowignore
@@ -1,2 +1 @@
-dist
 node_modules
diff --git a/now.json b/now.json
index 87a0dd6..25b6e79 100644
--- a/now.json
+++ b/now.json
@@ -1,4 +1,10 @@
 {
-  "version": 1,
-  "name": "ng-universal"
+  "version": 2,
+  "name": "ng-universal",
+  "builds": [
+    {
+      "src": "./dist/app/server/main.js",
+      "use": "@now/node-server"
+    }
+  ]
 }
diff --git a/package.json b/package.json
index 41ab2e7..0a4012a 100644
--- a/package.json
+++ b/package.json
@@ -11,9 +11,7 @@
     "dev:spa": "ng serve --hmr",
     "test": "ng test",
     "lint": "ng lint",
-    "e2e": "ng e2e",
-    "now-build": "ng run angular:udk:production",
-    "now-start": "node ./dist/app/server/main.js"
+    "e2e": "ng e2e"
   },
   "private": true,
   "dependencies": {
```

**Comment by jdgamble555** [comment]
Has anyone gotten this to work with current Vercel?  I tried something like this, but it does not work:

```typescript
{
  "version": 2,
  "public": true,
  "name": "test-universal",
  "builds": [
    { "src": "package.json", "use": "@vercel/static-build" },
    { "src": "./dist/test/server/main.js", "use": "@vercel/node" }
  ],
  "routes": [{ "src": "/(.*)", "dest": "./dist/test/server/main.js" }]
}
```

J
