### ISSUE TITLE
window is not defined AND localStorage is not defined errors in terminal

### ISSUE THREAD

**Issue by thecodeguru360** [enten/angular-universal#27]
I am having trouble by using window object and localStorage in my app. Can you help me how to fix it? I need both to work in browser.
Errors:

`ERROR { Error: Uncaught (in promise): ReferenceError: localStorage is not defined
ReferenceError: localStorage is not defined`
`ERROR { Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined`

**Comment by enten** [comment]
I’m not available until 27th February to investigate your issue.

But I guess the error append during the server side rendering. Keep it mind that node.js doesn’t know about browser stuff as window object.

The fatest but dirty way to avoid that kind of error is to put your piece of code which use the window object into a if-condition as like typeof window !== 'undefined'

**Comment by thecodeguru360** [comment]
It doesn't solve "window not defined" issue. Need help.

**Comment by enten** [comment]
Do you have a repo which reproduce your issue? I will investigate asap.

**Comment by thecodeguru360** [comment]
After applying checks for undefined all over the app, there is no error showing at node terminal but application is not loading in browser. After couple of minutes browser says "This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE"

There is no error at browser console or server terminal. 
One more thing; while i was facing window is not defined whole app did load in browser.

Server terminal is showing console logs fine, which i have added to app.

**Comment by enten** [comment]
@lahashmi  
How about using [angular dependency injection](https://angular.io/guide/dependency-injection) and create a service to wrap the [local storage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)?

Below a simple example where we create a null local storage API on the server side.

In that way, we only need to inject the `LocalStorageService` to use the localStorage API without test browser or server side every time.

Later, if you need to share the localStorage for each user between server and browser sides (by using [node-continuation-local-storage](https://github.com/othiym23/node-continuation-local-storage) and [angular transfer state API](https://angular.io/api/platform-browser/TransferState) for example): there will be only once service to update (the LocalStorageService).

```ts
export const LOCAL_STORAGE_API = new InjectionToken<Storage>('LOCAL_STORAGE', {
  providedIn: 'root',
  factory: universalLocalStorageAPIFactory,
});

export function browserLocalStorageAPIFactory(): Storage {
  return window.localStorage;
}

export function nullLocalStorageAPIFactory(): Storage {
  return {
    length: 0,
    clear: () => {},
    getItem: (_key) => null,
    key: (_index: number) => null,
    setItem: (_key, _value) => {},
    removeItem: (_key) => {},
  };
}

export function universalLocalStorageAPIFactory(): Storage {
  return typeof window !== 'undefined'
    ? browserLocalStorageAPIFactory()
    : nullLocalStorageAPIFactory();
}

@Injectable({
  providedIn: 'root',
})
export class LocalStorageService implements Storage {
  constructor(
    @Inject(LOCAL_STORAGE_API) readonly localStorageAPI: Storage,
  ) { }

  get length() {
    return this.localStorageAPI.length;
  }

  clear() {
    this.localStorageAPI.clear();
  }

  getItem(key) {
    return this.localStorageAPI.getItem(key);
  }

  key(index: number) {
    return this.localStorageAPI.key(index);
  }

  removeItem(key) {
    this.removeItem(key);
  }

  setItem(key, value) {
    return this.localStorageAPI.setItem(key, value);
  }
}
```

**Comment by thecodeguru360** [comment]
I have tried your suggested solution and also suggested in this article https://medium.com/@maciejtreder/angular-server-side-rendering-with-ng-toolkit-universal-c08479ca688
Errors are completely gone when i try any of solution above, but browser does not load application after there is no error. 
Cases:
1- When there is window and localStorage error, webpage loads see http://207.246.80.101:4000/#/
2- When there is no error or when i comment usage of window and localStorage implementation, webpage never loads see http://207.246.80.101:4100/

Any help? Thanks for suggestions.

**Comment by enten** [comment]
@lahashmi  
I checked the both URLs:
* Application load on :4000 ;
* Nothing append on :4100.

I can investigate but I need to reproduce your issues on local (to have an access to the server).

**Can you share a repository which reproduce your issues?**

**Comment by thecodeguru360** [comment]
@enten You can build this code to investigate issue. 
Invitation is here.
https://github.com/lahashmi/loading_error/invitations

Thanks again.

**Comment by enten** [comment]
@lahashmi I will try to investigate this week end.

**Comment by enten** [comment]
@lahashmi  
I run your code on my computer: I don't see issue with window or localStorage.

**I don't see any response in the browser because the socket connection (opened by the SocketService) is never closed on server side.**

For each node request which use express engine render: a socket connection is open and server side rendering sill waiting until the socket connection closes.

_Closing the socket connection will fix your issue._

I suggest to close the socket connection [on server side only](https://angular.io/api/common/isPlatformServer) when all data are loaded with the DataService.

Note that data loading will occur two times: during the server side rendering (server side) and the client side rendering (browser side).

A generic solution is to use a cache in your DataService and [transfer its state](https://angular.io/api/platform-browser/TransferState) from server to browser.  
The [same pattern is used with angular-apollo](https://github.com/apollographql/apollo-angular/blob/master/docs/source/recipes/server-side-rendering.md#store-rehydration) to avoid running graphql calls on server and browser sides.

**Comment by thecodeguru360** [comment]
I have wrapped the socket connection code only for browser by using isPlatformBrowser. Now everything working great. 
Your help is appreciated, Thank you so much.
