### ISSUE TITLE
How to keep state across module reloads

### ISSUE THREAD

**Issue by dvaldivia** [enten/angular-universal#28]
I'm wondering how can I prevent the HMR module to reload a specific service so I can keep state across reloads?

**Comment by enten** [comment]
Do you want to keep state across reload in browser side?

I think **it's possible to achieve that with [@angularclass/hmr](https://github.com/PatrickJS/angular-hmr)**: its [README](https://github.com/PatrickJS/angular-hmr#readme) provide an example.

There is two important parts:
* Call [`hmrModule()`](https://github.com/PatrickJS/angular-hmr/blob/master/src/hmr.ts#L10) with app browser module ref ;
* Add methods `hmrOnInit()`, `hmrAfterDestroy(data)` and `hmrAfterDestroy(data)` in the app browser module.

**Comment by dvaldivia** [comment]
I figured that in `main.ts` you can use `const booting = boot().then((mod) => {` to perform an action on booting the HMR and then `module.hot.dispose(() => {` to save the sate, so that's how I did it
