### ISSUE TITLE
HMR not working correctly - entire app reloads on change

### ISSUE THREAD

**Issue by eyalhakim** [enten/angular-universal#33]
When making a change in a component, the entire app is reloaded, discarding the current state.

I get an output:

`[HMR] Updated modules:

index.js:3671 [HMR]  - ./node_modules/raw-loader!./src/app/login.component/login.component.html

index.js:3671 [HMR]  - ./src/app/login.component/login.component.ts
index.js:3671 [HMR]  - ./src/app/app-routing.module.ts
index.js:3671 [HMR]  - ./src/app/app.module.ts
index.js:3671 [HMR]  - ./src/app/app.browser.module.ts
index.js:3671 [HMR]  - ./src/main.ts
index.js:3671 [HMR] App is up to date.
index.js:3671 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
index.js:3671 AppBrowserModule boostraped! `

I do not use lazy loaded modules.

Any idea what could cause this?

**Comment by thedewpoint** [comment]
@eyalhakim HMR stands for hot module replacement. this is a development feature when you are working locally so you dont have to recompile your entire app every time you make a change.

**Comment by eyalhakim** [comment]
@thedewpoint thanks for your answer! I'm aware what HMR is, and this issue is about HMR not functioning correctly.

When looking at the library that provides it, `https://github.com/PatrickJS/angular-hmr`, I can see that the state should be preserved on module reload (shown in the GIF on the readme).

However, in my case, this doesn't happen, but instead the entire app reloads and state is lost.

Any idea what could cause this?

**Comment by enten** [comment]
@eyalhakim 
As angular hmr warning says: **to take advantage of HMR additional application code is required**.

In this repository: we setup hmr on browser and server sides.

### HMR on browser side

The only hmr code written on browser side is in browser entry point [src/main.ts#L18](https://github.com/enten/angular-universal/blob/551792b/src/main.ts#L18).


```ts
const ngModuleRef = await platformBrowserDynamic().bootstrapModule(AppBrowserModule);

// HMR on browser side
if (module.hot) {
  module.hot.accept();

  module.hot.dispose(async () => {
    const appRef = ngModuleRef.injector.get(ApplicationRef);
    const elements = appRef.components.map(c => c.location.nativeElement);
    const makeVisible = createNewHosts(elements);

    ngModuleRef.destroy();

    makeVisible();
  });
}
```

The hmr code written allows to apply webpack hmr chunks at application bootstrap level without needs a full page reload (that outputs `[HMR] App is up to date.` log that you copy/paste in your first post).

If you needs to save and restore application state, you can adust code in the same way as [angular/class hmr example in README](https://github.com/PatrickJS/angular-hmr).

Or you can simply use `module.hot.dispose()` in browser main entry to call manually some ngModuleRef.instance methods used for keep state when application hot reloading.

You can read more about HMR by visiting [webpack hmr docs](https://webpack.js.org/guides/hot-module-replacement/).

### HMR on server side

You don't need to write hmr code on server side for your needs.

Please note that this repo supports hmr on server side too.

If you need to add hmr for some new lazy modules (for example): all hmr code on server side is in server entry point [src/server.ts#L54](https://github.com/enten/angular-universal/blob/a6486d0/src/server.ts#L54).

```ts
// HMR on server side
if (module.hot) {
  const hmr = () => {
    try {
      const { AppServerModuleNgFactory } = require('./app/app.server.module.ngfactory');
      exports.AppServerModuleNgFactory = AppServerModuleNgFactory;
    } catch (err) {
      console.warn(`[HMR] Cannot update export of AppServerModuleNgFactory. ${err.stack || err.message}`);
    }

    try {
      const { WelcomeModuleNgFactory } = require('./app/welcome/welcome.module.ngfactory');
      exports.LAZY_MODULE_MAP['./welcome/welcome.module#WelcomeModule'] = WelcomeModuleNgFactory;
    } catch (err) {
      console.warn(`[HMR] Cannot update lazy module WelcomeModule. ${err.stack || err.message}`);
    }

    try {
      requestListener = require('./api').createApi(BROWSER_DIST_PATH, getNgRenderMiddlewareOptions());
    } catch (err) {
      console.warn(`[HMR] Cannot update server api. ${err.stack || err.message}`);
    }
  };

  module.hot.accept('./api', hmr);
  module.hot.accept('./app/app.server.module.ngfactory', hmr);
  module.hot.accept('./app/welcome/welcome.module.ngfactory', hmr);
}
```

**Comment by eyalhakim** [comment]
@enten  Got it, thank you!
