### ISSUE TITLE
TransferStateModule not being used

### ISSUE THREAD

**Issue by eyalhakim** [enten/angular-universal#36]
ServerTransferStateModule and BrowserTransferStateModule should be used in order to send cached server http results to client.

**Comment by enten** [comment]
@eyalhakim 
Is it a question? or a feature request to integrate in repo?

Branch [feat/app-config](https://github.com/enten/angular-universal/tree/feat/app-config) uses TransferStateModule to demonstrate [how we can share config from server to browser](https://github.com/enten/angular-universal/commit/7eba3ccfddca2c84e7da992728dbe2ae5ed84bba).

**Comment by eyalhakim** [comment]
Sorry I was referring to TransferHttpCacheModule from @nguniversal/common

**Comment by enten** [comment]
@eyalhakim 
Do you suggest to add [this feature example](https://github.com/angular/universal/blob/master/docs/transfer-http.md) in the base repo?
