### ISSUE TITLE
What is the difference between this repo and angular/universal-starter ?

### ISSUE THREAD

**Issue by vbourdeix** [enten/angular-universal#37]
I found this repository as well as https://github.com/angular/universal-starter, and I would want to know why / when it would be more appropriate to use your repository or the official one ?

**Comment by enten** [comment]
In few words: this repository produce browser and server bundles in one build (with only once webpack configuration).

The official repository need two or three separate builds (like in [ssr official example](https://angular.io/guide/universal) to create all needed bundles (one which is the app for browser, one which is the app for server and one which is the server).

A good dev feature (which missing from the official repository): this repository support a dev mode which enable hot module reloading in both browser and server side.

You can try boths repository (and their scripts) to make your opinion.

**Comment by vbourdeix** [comment]
Ok, I understand, thanks for the quick reply 👍 . Hot reloading sounds like a valid point indeed.
