### ISSUE TITLE
error with current build    

### ISSUE THREAD

**Issue by thedewpoint** [enten/angular-universal#38]
had to update this version to be static, when it pulls in a newer version it is missing differential loader.  
  "@angular-devkit/build-angular": "0.800.2",

Below is the error I got
Cannot find module '@angular-devkit/build-angular/src/utils/differential-loading'
Error: Cannot find module '@angular-devkit/build-angular/src/utils/differential-loading'

**Comment by enten** [comment]
Did you update to last version of angular-devkit/build-angular?
That sound like a version issue: [this commit](https://github.com/angular/angular-cli/commit/a29bf4ec36f30d461baa45757fd62d6910eac26d#diff-28106653c2c8aee05ff7a1a0aab07380) change differential-loading location.

**Comment by thedewpoint** [comment]
No I downgraded

**Comment by enten** [comment]
@thedewpoint 
My bad. You're right there is a change in the angular devkit build angular which rename utils `differential-loading.ts > build-browser-features.ts`.

I'm working to publish an update of udk to fix that.

**Comment by enten** [comment]
@thedewpoint 
I pubished udk v1.1.1 to handle the change.

Can you check if that fix your issue?

**Comment by enten** [comment]
I think I had an answer to this issue.

Lot of things change related with differential browser build.

Previously, that was 2 webpack builds (one for es2015 and another for es5).

In last version, angular devkit has 1 webpack build for es2015 only.
When es5 version is needed, angular will downlevel es2015 files to es5 with babel.

**Can you try to update to angular v9.0.0-rc.6 and udk v1.1.9-rc.1 (as the boilerplate) and check if your issue is solved?**

```
npm install @angular/animations@9.0.0-rc.6 @angular/common@9.0.0-rc.6 @angular/compiler@9.0.0-rc.6 @angular/core@9.0.0-rc.6 @angular/forms@9.0.0-rc.6 @angular/http@8.0.0-beta.10 @angular/platform-browser@9.0.0-rc.6 @angular/platform-browser-dynamic@9.0.0-rc.6 @angular/platform-server@9.0.0-rc.6 @angular/router@9.0.0-rc.6 @angularclass/hmr@2.1.3 @nguniversal/express-engine@8.2.6 @nguniversal/module-map-ngfactory-loader@v8.2.6

npm install --save-dev @angular-devkit/build-angular@0.900.0-rc.6 @angular/cli@9.0.0-rc.6 @angular/compiler-cli@9.0.0-rc.6 @angular/language-service@9.0.0-rc.6 typescript@3.6.4 udk@1.1.9-rc.1
```
