### ISSUE TITLE
Lazy loading modules does not work with new syntax

### ISSUE THREAD

**Issue by christostatitzikidis** [enten/angular-universal#39]

**Comment by christostatitzikidis** [comment]
does not work:  loadChildren: () => import('./modules/container.modules/home.container.module/home.container.module').then(m => m.HomeContainerModule)

works: loadChildren: './modules/container.modules/home.container.module/home.container.module#HomeContainerModule'

**Comment by enten** [comment]
Did you update to angular 8?

Because it's a new feature (check angular [realease 8 blog post](https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27#b722)).

**Comment by christostatitzikidis** [comment]
Yes what I mean is that when LoadChildren  uses the new dynamic import syntax the module is not lazy loaded but is included in the main module. For example the welcome module in the starter kit is not lazy loaded any more.

**Comment by christostatitzikidis** [comment]
When I compile the same code (dynamic imports) without the UDK several modules are created (both for ES2015 and ES5). When I compile with the UDK I get one big main.js file. If I don’t use the dynamic imports I get modules but not two separate ones for es5/es2015. Also they are a lot larger than the ones made by the angular compiler without UDK.

**Comment by enten** [comment]
@christostatitzikidis 
My bad. I made a mistake in the workspace tsconfig.json.
I will push a commit to fix that.

```diff
diff --git a/tsconfig.json b/tsconfig.json
index ef44e28..607415f 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -5,10 +5,11 @@
     "outDir": "./dist/out-tsc",
     "sourceMap": true,
     "declaration": false,
+    "module": "esnext",
     "moduleResolution": "node",
     "emitDecoratorMetadata": true,
     "experimentalDecorators": true,
-    "target": "es5",
+    "target": "es2015",
     "typeRoots": [
       "node_modules/@types"
     ],
```

**Comment by enten** [comment]
@christostatitzikidis
*Can you try to fetch update or apply the patch and tells us if lazy route as import works again?*

**Comment by christostatitzikidis** [comment]
Yes, it works on this repository :) thanks! I'll try it tomorrow at work on the project I'm working on (40+ lazy loaded modules) and let you know if I find any other issues. Good job and thanks btw, been using this for a good while and now it seems to be even better with supporting HRM on lazy routes. Thanks again for the quick response and fix!

**Comment by enten** [comment]
@christostatitzikidis 
> 40+ lazy loaded modules

Waw! And everything building in the same universal compilation?

I'm waiting that you test at your work before close this issue :)

**Comment by christostatitzikidis** [comment]
All seems to be working fine now :). Please close.
