### ISSUE TITLE
Error with latest master

### ISSUE THREAD

**Issue by wundo** [enten/angular-universal#47]
I'm experiencing this showing up in the Chrome console:

```[HMR] Update check failed: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (http://localhost:4000/runtime.js:103:34)
    at XMLHttpRequest.wrapFn (http://localhost:4000/polyfills.js:1231:43)
    at ZoneDelegate.invokeTask (http://localhost:4000/polyfills.js:412:35)
    at Zone.runTask (http://localhost:4000/polyfills.js:180:51)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4000/polyfills.js:493:38)
    at invokeTask (http://localhost:4000/polyfills.js:1634:18)
    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:4000/polyfills.js:1660:21)```

Google has failed me, the only mention I found is #1, which is very old and was fixed by updating a package version. Do you know what may be causing it?

**Comment by enten** [comment]
> I'm experiencing this showing up in the Chrome console

Which version of chrome do you use?

> Google has failed me, the only mention I found is #1, which is very old and was fixed by updating a package version

Which package did you updated?

> Do you know what may be causing it?

As the piece of error stack trace said: I think there is somewhere an error with a JSON parse.

The best way to investigate is to share a repo which reproduce the issue.

**Comment by wundo** [comment]
Hi @enten thanks for the follow up 😄 

> Which version of chrome do you use?

Version 84.0.4147.125 (Official Build) (64-bit)


> Which package did you updated?

I didn't update anything, in #1 the suggested solution was updating a package, but given that is 2 years would I guessed HEAD would be updated by now.

> As the piece of error stack trace said: I think there is somewhere an error with a JSON parse.

Ok, I will try to to reproduce with starting from the scratch again

**Comment by wundo** [comment]
@enten I have a clue, here is the screenshot of what is causing the error:

<img width="1149" alt="Screen Shot 2020-08-16 at 12 06 46 PM" src="https://user-images.githubusercontent.com/113942/90337466-fffd7a80-dfb8-11ea-9fbc-49099afc65f2.png">

Does it gives you any idea?

**Comment by wundo** [comment]
Hi @enten sorry for bothering you with this, my Chrome was having some really weirdo caching issues.
