### ISSUE TITLE
Support for Angular 11

### ISSUE THREAD

**Issue by yackinn** [enten/angular-universal#48]
I tried to make some adjustments but the udk library doesn't seem to work as it depdends on the Angular 10 devkit builder.
Do you want to provide support for Angular 11?

**Comment by enten** [comment]
> Do you want to provide support for Angular 11?

Yes, the lastest commit (2ffeab6) provides Angular 11.0.3 support. It requires latest version of udk ([v1.1.11-rc.0](https://github.com/enten/udk/tree/v1.1.11-rc.0)).

@yackinn
_Can you tell me if every works as you expected?_

**Comment by yackinn** [comment]
@enten 
I'm not sure how the estup is supposed to be with @nestjs/ng-universal.

This is invoked.
ng run server:serve-ssr

The angular.json is setup like this.

```json
"server": {...
	  "serve-ssr": {
	            "builder": "@nguniversal/builders:ssr-dev-server",
	            "options": {
	              "browserTarget": "ui:build",
	              "serverTarget": "server:build"
	            },
			...
}

"ui": {...
	  "architect": {
	          "build": {
	            "builder": "@angular-builders/custom-webpack:browser",
	            "options": {
				  ... no builder is setup in this options property
}

"server": {
	  "architect": {
	          "build": {
	            "builder": "@angular-builders/custom-webpack:server",
	            "options": {
				... no builders
		...
}
```
What should the setup be like using udk?
The nestjs server serves the html in the current setup.

**Comment by yackinn** [comment]
It should work.
Instead of using the express api I'm using the nestjs server.

That's the reconfigured server.ts.

It won't work though. It'll invoke the dev server but that's it

```ts
// AppSsrModule is the AppServerModule that Angular universal will create
export { AppSsrModule as AppServerModule } from '../ui/src/app/app.ssr.module';

if (environment.production) {
  enableProdMode();
}


// HMR on server side
if ((module as any).hot) {
  let AppServerModuleHot = AppSsrModule;

  const hmr = () => {
    try {
      AppServerModuleHot = require('../ui/src/app/app.ssr.module').AppSsrModule;
    } catch (err) {
      console.warn(`[HMR] Cannot update export of AppServerModule. ${err.stack || err.message}`);
    }
	
	// main.server.ts is the nestjs main.ts file
    (module as any).hot.accept('./src/main.server.ts', hmr)
    (module as any).hot.accept('../ui/src/app/app.ssr.module', hmr);
  };
}


/**
 * SERVER
 */
let server;

if (environment.production) {

} else {
  const mainModule     = __non_webpack_require__.main;
  const moduleFilename = (mainModule && mainModule.filename) || '';

  server = bootstrapLocal()  // simple nestjs main.ts bootstrap function
}

export default server
```

<img width="547" alt="Bildschirmfoto 2020-12-18 um 21 23 31" src="https://user-images.githubusercontent.com/61085055/102658173-55b87e00-4177-11eb-8377-08e20143a239.png">

**Comment by enten** [comment]
@yackinn 
I need to read some parts of the source code (and the angular.json) to investigate.
Can you share a repo which reproduce your issue?

But there is an importants things to do in the server main file which `export default server`.

In this repo, you can notice that the server created is a just a wrapper arround the http request handler (`requestListener`).
And the hmr handler updates http request listener.
In that way, we create and export the http server once (hmr handler shouldn't create a new server).

```ts
// ...
let requestListener = createApi(getServerAPIOptions(AppServerModule));

// Create the Node server
const server = createServer((req, res) => {
  requestListener(req, res);
});

// HMR on server side
if (module.hot) {
  let AppServerModuleHot = AppServerModule;

  const hmr = () => {
    try {
      AppServerModuleHot = require('./app/app.server.module').AppServerModule;
    } catch (err) {
      console.warn(`[HMR] Cannot update export of AppServerModule. ${err.stack || err.message}`);
    }

    try {
      requestListener = require('./api').createApi(getServerAPIOptions(AppServerModuleHot));
    } catch (err) {
      console.warn(`[HMR] Cannot update server api. ${err.stack || err.message}`);
    }
  };

  module.hot.accept('./api', hmr);
  module.hot.accept('./app/app.server.module', hmr);
}

// ...

// WARN: don't remove export default of server .
// Removing export below will break universal dev server.
export default server;
```

**Comment by yackinn** [comment]
@enten 
Thanks for your answer.
It's been a few months.
I'm looking more into implementing hmr with Angular universal and Nestjs.

It's basically this setup.
https://github.com/TrilonIO/universal-nest

Instead of using a simple express server Nestjs is used.

The ngexpressengine isn't exposed directly. It's inside the ng-universal package.
https://github.com/nestjs/ng-universal/blob/master/lib/utils/setup-universal.utils.ts

Do you think you can support me adding hmr functionality to this setup?

**Comment by enten** [comment]
@yackinn 
I checked nestjs/ng-universal and I noticed that it's work with files produced by angular builders:: is that right?

Unfortunately it's impossible to setup hmr with this approach. In fact, HMR only works with webpack compilation.
But I thinks it's not a problem because as nestjs/ng-universal works with static files normally after agular builders done you should see the latest version in the browser: isn't it?
