### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by shawndotey** [enten/angular-universal#5]
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\scran\Source\Repo\universal-enten\$npm_package_main'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by enten** [comment]
**I think you issue is the same as #3. Do you use Windows?**

> I think the error `Error: Cannot find module 'L:\ng-universal$npm_package_main'` is thrown because npm not dynamically replace `$npm_package_main` by the `package.json` _main_ field.
> 
> I encountered this issue on a windows environment too. But I don't know if it's inherent to windows or a previous npm version (I don't investigate that issue yet because I don't have it on my main dev platform).
> 
> **You may fix this issue by update your `package.json` to avoid use of the dynamic reference > `$npm_package_main`.**
> 
> ```diff
> -    "start": "node $npm_package_main",
> +    "start": "node "dist/app/server/main.js",
> ```

**Comment by shawndotey** [comment]
That worked, thanks! FYI I am using windows npm 5.6.0.
