### ISSUE TITLE
assets folder is not copied to dist/app/browser

### ISSUE THREAD

**Issue by balighbelgacem** [enten/angular-universal#52]
After running ng serve the assets folder is missing in dist/app/browser. The build doesn't seem to copy the assets folder to dist.

**Comment by enten** [comment]
@balighbelgacem 
Which versions do you use?

Today I updated this repo to make work it works with angular v11.2.8 (udk v1.1.11-rc.2 needed).
When I run `ng serve` and create file under assets folder: the dev server notify the change, and copy the new file.

**Comment by balighbelgacem** [comment]
It is fixed with the last commit. The asstes folder is now copied to dist/app/browser.
Thank you very much.
