### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by bolota** [enten/angular-universal#6]
Hi, 

I'm trying to use your work with ng-bootstrap and i get: 

import { forwardRef, Inject, Directive, Input, Output, EventEmitter, ElementRef, ContentChild, NgZone, Renderer2 } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import

Thanks

**Comment by enten** [comment]
Can you share a repository which reproduce your issue? I will investigate it as soon as possible.

**Comment by enten** [comment]
@bolota  
I think that issue is due to the ng-bootstrap package on server side: it seems to be include in the bundle.

**Which is the file which throws that exception?** Is it a file under the ng-bootstrap package?

**Comment by harshithmullapudi** [comment]
Hey I am getting the same error 
```
rshith\my-project\node_modules\@angular\fire\bundles\messaging.umd.js:23
                var requireMessaging = rxjs.from(import('firebase/messaging'));
                                                 ^^^^^^

SyntaxError: Unexpected token import
```

**Comment by enten** [comment]
@harshithmullapudi 

Where this error is displayed: in the server or browser side?

Can you try to set option `bundleDependencies` to `"all"` in your browser or server target (depends where your error appears) configuration in the `angular.json`?

if you're not familiarise with the `angular.json` format: you can found [example in this comment](https://github.com/enten/angular-universal/issues/2#issuecomment-387314558).
