### ISSUE TITLE
How to integrate socket.io with this project?

### ISSUE THREAD

**Issue by sweety-wo** [enten/angular-universal#7]
Is it possible to integrate socket.io with this project? 
I want to integrate socket.io with angular-universal (MEAN stack project).
I have clone this project  and successfully runing but when I try to integrate socket.io with it then web page is just getting load not showing any view on page, Just getting load.

Can you please provide steps for integrate socket.io?

**Comment by enten** [comment]
@sweety-wo   
Yes I can.  
Can you share repository with which you have tried to integrate socket.io?  
I will write the patch to make your code work.
