### ISSUE TITLE
Is it possible to separate the server files in development environment?

### ISSUE THREAD

**Issue by webosmotic-developer** [enten/angular-universal#8]
Currently, the server files reside in the src folder in the development environment.

I want all the server files i.e. .api.ts' & 'main.server.ts' outside of src folder in a different folder.

So, I have created a new folder called 'server' in the root directory and I removed the above-mentioned files from src and added them into a server. Actually, I want to create node API server so, I want to create separately server folder.

Then, I changed the path of file 'angular.json' as follows:

![screenshot from 2018-06-12 18-19-33](https://user-images.githubusercontent.com/30309288/41291645-e88f4edc-6e6d-11e8-86a8-249258503e23.png)

and in file 'udk.container.js' as follows:

![screenshot from 2018-06-12 18-20-58](https://user-images.githubusercontent.com/30309288/41291665-f6be5340-6e6d-11e8-8fe4-d3174ee93727.png)

Then I enter 'npm start' in terminal but I get the following error:

>   ERROR in ./server/main.server.ts
  Module build failed: Error: /home/webosmotic/projects/universal/angular-universal/server/main.server.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
      at AngularCompilerPlugin.getCompiledFile (/home/webosmotic/projects/universal/angular-universal/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:708:23)
      at plugin.done.then (/home/webosmotic/projects/universal/angular-universal/node_modules/@ngtools/webpack/src/loader.js:41:31)
      at <anonymous>

![screenshot from 2018-06-12 18-25-31](https://user-images.githubusercontent.com/30309288/41291734-22a89f7e-6e6e-11e8-9e0c-48b6a5ad554e.png)

I am not able to find a solution for this...If anyone have a workaround for this please let me know.

**Comment by enten** [comment]
@webosmotic-developer  
Yes is it possible. 
Can you share your repository?  
I will write the patch to do that.
