### ISSUE TITLE
Prod Build

### ISSUE THREAD

**Issue by Ascone82** [enten/angular-universal#9]
I've a problem in production server. I don't know why start my SPA with PM2. In older versions of Angular Universal (like 5 ver) I copy the server.js file from the dist/server folder into my vhost root folder and I start it with PM2 than in this Angular Universal by Enten I have not a file called server.js. I need help. Thanks a lot.

**Comment by enten** [comment]
In Angular 5, all server dependencies was included in the server bundle.

In Angular 6, all externals dependencies are excluded by default.

You can use the options `"bundleDependencies": "all"` in the server target to include all dependencies in your server bundle.
In that way, you will be able to only upload `dist/app/server/main.js` (and `dist/app/browser` folder of course).

Ensure to update your repository with the latest revision of [angular-universal](https://github.com/enten/angular-universal/).

There are more information about that practice in #2 [Requires a dependency for production](https://github.com/enten/angular-universal/issues/2).

```diff
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json",
+           "bundleDependencies": "all"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
```
